### ISSUE TITLE
No interface ICaseSite in https://api-trade.opskins.com

### ISSUE THREAD

**Issue by darkwar123** [vgoskins/vcase#2]
Check screenshot, please 
![default](https://user-images.githubusercontent.com/10097271/41790959-ee7859be-765c-11e8-95bb-5c423cf92c0b.JPG)

**Comment by daniandl** [comment]
I suggest waiting a few days for them to actually implement everything

**Comment by QuantumLlama** [comment]
Hello,

You can only access these endpoints with a special user. You can create this user via  [IUser/CreateVCaseUser](https://github.com/OPSkins/trade-opskins-api/blob/master/IUser/CreateVCaseUser.md)

P.S. endpoints under ICaseSite should now return 401 instead of 404 if you are not using a special user API key.

**Comment by QuantumLlama** [comment]
Hello,

You can only access endpoints under ICaseSite with a special user. You can create this user via [IUser/CreateVCaseUser](https://github.com/OPSkins/trade-opskins-api/blob/master/IUser/CreateVCaseUser.md)

P.S. these endpoints should now return a 401 instead of 404 if you try to access with normal API key.

**Comment by darkwar123** [comment]
@QuantumLlama thank you very much <3

But now I have a new issue when my users open cases I don't receive 5% on my ether wallet :)

**Comment by gabenthegamer** [comment]
@darkwar123 I do not get 5% Either tested with 2 wallets

**Comment by darkwar123** [comment]
@gabenthegamer I send the letter to vgohelp@gmail.com. Hope they will help us.

**Comment by gabenthegamer** [comment]
Ok :D

**Comment by KillRoy9321** [comment]
I've tested it with 4 different address and same problem, Sent an email 2 days ago and still no reply.

**Comment by darkwar123** [comment]
@KillRoy9321 :-(

**Comment by gabenthegamer** [comment]
@darkwar123 Add me on steam : BobTheShoplifter
